#include "compute.c"
#pragma config(Sensor, S2,     gyro,           sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	computeDegree(int height, int degree);
}