#pragma config(Sensor, S3,     color,          sensorEV3_Color, modeEV3Color_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	string colstr = colorNone;
	while(1) {
		switch(SensorValue[color])
		{
			case 1: playTone(523, 50); break;
			case 2: playTone(587, 50); break;
			case 3: playTone(659, 50); break;
			case 4: playTone(698, 50); break;
			case 5: playTone(784, 50); break;
			case 6: playTone(880, 50); break;
			case 7: playTone(987, 50); break;
			default: break;
		}
		sleep(500);
	}
}
