#pragma config(Sensor,  S2,     Gyro,       sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration

task main()
{
	int LV = SensorValue[Gyro];
	while(1)
	{
		writeDebugStream("Gyro: %d", SensorValue[Gyro]);
		writeDebugStream("motorC: %d", motor[motorC]);
		motor[motorB] = 30;
		motor[motorC] = 30+(SensorValue[Gyro]-LV);
	}
}
//Program: Robot always go straight if it will be trubble
