#pragma config(Sensor, S1,     touch,          sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1)
	{
		while(SensorValue[touch] == 0){}
		while(SensorValue[touch] == 1){}
		setLEDColor(7);
		motor[motorB] = 50;
		motor[motorC] = 50;
		wait1Msec(1000);

		while(SensorValue[touch] == 0){}
		while(SensorValue[touch] == 1){}
		setLEDColor(8);
		motor[motorB] = -50;
		motor[motorC] = -50;
		wait1Msec(1000);

		if(getButtonPress(buttonUp))
		{
			setLEDColor(9);
			motor[motorB] = 50;
			motor[motorC] = 50;
			wait1Msec(1000);
		}
		else if(getButtonPress(buttonDown))
		{
			setLEDColor(8);
			motor[motorB] = -50;
			motor[motorC] = -50;
			wait1Msec(1000);
			playTone(440, 100);
		}
	}
}
